name: Preview Apps POC
on:
  pull_request:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Debug
        uses: hmarr/debug-action@v2
      - name: Deploy Hasura Cloud preview app
        env:
          CLOUD_DATA_GRAPHQL_ENDPOINT: "https://c100-106-51-72-39.ngrok.io/v1/graphql"
          GITHUB_PAT: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          HASURA_CLOUD_PAT: ${{ secrets.HASURA_CLOUD_ACCESS_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          HASURA_PROJECT_DIR_PATH: "hasura"
        run: |
          ${{ github.workspace }}/scripts/deploy-preview-app.sh
      - run: echo "🍏 This job's status is ${{ job.status }}."
